### PR TITLE
parse vectornav ins data

### PR DESCRIPTION
**Pull request by abbymartin**

### CODE REVIEW

**Review by RCMast3r — CHANGES_REQUESTED** [review]
pls update the input in flake.nix for HT_proto after you merge it into master

**Review by RCMast3r — CHANGES_REQUESTED** [review]
https://github.com/hytech-racing/drivebrain_software/actions/runs/11559003872/job/32172691554

looks like this is attempting to use the previous version of the HT_Proto that still has the spelling error

**Comment by abbymartin** [comment]
> https://github.com/hytech-racing/drivebrain_software/actions/runs/11559003872/job/32172691554
> 
> looks like this is attempting to use the previous version of the HT_Proto that still has the spelling error

just realized this and should be fixed now

**Review by RCMast3r — APPROVED** [review]

**Comment by RCMast3r** [comment]
@abbymartin you will need to add another reviewer due to the current approval requirements on this repo

**Review by KrishKittur — APPROVED** [review]

**Pull request merged**
